# -*- coding: utf-8 -*-
"""Abhishek01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_nWqCtNJIaD6A_UhhynS8RM2FQ-ZZJYt
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

heart_data=pd.read_csv('/content/heart.csv')
heart_data.head()

heart_data.tail()

heart_data.shape

heart_data.info()

heart_data.isnull().sum()

heart_data.describe()

heart_data['target'].value_counts()
#1>>for defective heart
#0>>for healthy heart

X = heart_data.drop(columns='target', axis=1)
Y = heart_data['target']
print(X)

print(Y)

X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
print(X.shape, X_train.shape,X_test.shape)

model = LogisticRegression()
model.fit(X_train,Y_train)

X_train_prediction=model.predict(X_train)
training_data_accuracy =accuracy_score(X_train_prediction,Y_train)
print('Accuracy on training data = ',training_data_accuracy)

X_test_prediction=model.predict(X_test)
test_data_accuracy =accuracy_score(X_test_prediction,Y_test)
print('Accuracy on test data = ',test_data_accuracy)

input_data=(71,0,0,112,149,0,1,125,0,1,1,0,2)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction = model.predict(input_data_reshaped)
print(prediction)
if (prediction[0]==0):
  print("the person doesn't have heart disease")
else:
  print("the person has heart disease")